### ISSUE TITLE
crashing for no reason on startup

### ISSUE THREAD

**Issue by owwnd** [TheBritishBrotherhood/ArdentCraft-The-Beginning#113]
the launcher keeps crashing on startup the problem started when i killed a whither skeleten in the nether and it froze and crashed so i wanted to restart it then it showed me a error so i reinstalled it and pasted the saves folder i used is there again and it keeps crashing for no reason
[crash-2017-02-09_19.14.47-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/764588/crash-2017-02-09_19.14.47-client.txt)

i hope this will help

**Comment by owwnd** [comment]
i tested it again whit a clean install no save in the saves folder and it still is crashing now i cant even play the pack anymore please help
[crash-2017-02-09_19.26.49 2-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/764617/crash-2017-02-09_19.26.49.2-client.txt)

**Comment by Crystonyx** [comment]
I am having the same issue where it crashes on startup, so instead of starting a different issue post, I will just add to this one. 

[Here is my pastbin link for my crash file.](http://pastebin.com/yQ4TKRjG)

I have reinstalled the pack twice now while still failing to launch both times. I also have version 3.1.01 installed. I hope this issue can be fixed soon, or at least a solution to be found, as I have heard a lot of great things of this pack and would like to try it out.

**Edit:** Attempted to bump up the RAM usage from the standard curse settings of 4GB to 7GB and even 8GB
as was stated in the DecoCraft issue about needing 7GB to even run it, and nothing has changed. I currently have 16GB installed and also have a nvidia GPU, and have not updated my drivers due to issues with them.

After I hit play, and go through the blue loading bar at the bottom of MineCraft, instead of the game launching and starts initializing it just has the crash window appear in the launcher.

**Comment by TheBritishBrotherhood** [comment]
Cealian:

For those NVIDIA users who are having problems starting the pack since the latest drivers, checkout these hotfix drivers http://nvidia.custhelp.com/app/answers/detail/a_id/4378/ That helped me to get it to work

Try this guys :)
