### ISSUE TITLE
Minecraft has run out of memory 

### ISSUE THREAD

**Issue by nboltz21** [TheBritishBrotherhood/ArdentCraft-The-Beginning#19]
Hi I just Installed your mod pack after watching The Only Bentley watch it I get a error saying I have run out of memory I have 16gb installed Please Help!!!

**Comment by cainer98** [comment]
I also found that more memory was being use than I had allocated in the curse launcher. I had given 6gb and it was running at 7.5. I was also having fps issues after every time I died changing the fancy/fast graphics setting fixed the fps issue until another death but the memory issue persisted. Ill keep messing with settings and see if anything magics it away.

As for nboltz21's issue, depending on your launcher you can assign more memory to the game. In curse its done by clicking on the settings button on the bottom left and moving the slider under the minecraft submenu.

I like the pack though. Keep up the good work.

**Comment by TheBritishBrotherhood** [comment]
nboltz21 - You have to manually dedicate at-least 6gb ram or more to the pack :) 

cainer98 - Thanks for the awesome words :) The pack is ram heavy due to 1.10/Forge having a memory leak, Not much i can do about that issue at the moment. And as for the FPS lag, None of my testers or me have had this issue :/
