### ISSUE TITLE
Crash when trying to pick up agricraft seed analyzer

### ISSUE THREAD

**Issue by Joelee7648** [TheBritishBrotherhood/ArdentCraft-The-Beginning#30]
Crash log included. I placed the seed analyzer down, then wanted to move it, but everytimer I hit it once, i instantly crash. (I am using my hand to try to pick it up)

[crash-2016-12-17_07.40.18-client.txt](https://github.com/CurtisLee1994/ArdentCraft-The-Beginning/files/658848/crash-2016-12-17_07.40.18-client.txt)

**Comment by vincentmet** [comment]
Could you tell me if you were using anything related to one of CodeChicken's mods?

**Comment by Joelee7648** [comment]
No, only what's already included in the modpack

**Comment by Joelee7648** [comment]
Also, Agricraft itself isn't working at all; for example: when I plant
wheat inside of the crop sticks, they never grow, and it duplicates any
seeds you put into them. I start planting with two seeds, then I place 6
crop sticks; it plants but doesn't consume them.

If it will help, I make Youtube videos on this pack, and I can make a
spotlight for some of the problems I am having. Just let me know, because I
love the modpack, and would love to see it grow.
Not to mention, it will help my Livestream series I have going on.

Great job on the pack, and keep up the good work. Let me know if I can ever
help.

**Comment by vincentmet** [comment]
no, i ment like having I.E. an enderchest (from Chickenbones Enderchest mod) in your hotbar or next to the analyzer.

Oke, ill test this out myself this afternoon, and if i have the same problem, i will most likely remove agricraft untill its stable again.

I always love to see youtube video's of the pack! Please leave a link, so that ik can check it out sometimes.

If you would like, you could help if you are good at texture making! A am making a mod that will be used in bothe normal AND expert mode, but i really need textures for it, before i can realease it...Let me know if you are interested in that kind of helping :P

**Comment by TheBritishBrotherhood** [comment]
Fixed as of 2.7.00

Agricraft has been removed until stable.

**Comment by Joelee7648** [comment]
Thank you, that is both good news and bad news; good news because I can now
restart my series, but bad news because i love Agricraft.

I, also, meant to reply sooner and tell you that I would be very interested
in making a texture pack for you; I'm not the best, but I am sure i can
make something you'll love. just let me know what you'd like, and I'll
start on it in my free time.

**Comment by Joelee7648** [comment]
Just wanted your opinion on a GUI for the modpack, the theme I am thinking
of going with, based on the title screen artwork.
​

**Comment by vincentmet** [comment]
What do you mean?
