### ISSUE TITLE
Cast quests +1L rewards too small?

### ISSUE THREAD

**Issue by wolpoff** [TheBritishBrotherhood/ArdentCraft-The-Beginning#62]
Version 2.7.01

For the Getting Started->x Cast quests, the reward is +1L.  They do actually reward experience, but it's probably equivalent to the xp of level 1, not actually +1 level.  I've turned in a good 5 or so, while already at level 30. Almost don't notice them.  Took 5 before I could see that they'd incremented a notch or two on the experience bar.  They don't actually add a level.

By the time you're on these quests, unless you just died, they seem a bit small.  Just my personal opinion, but I'd make it bigger or more impactful.

**Comment by vincentmet** [comment]
That true, because otherwise, the levels are increasing exponential, instead of linear. It takes the amount of experience you have when you only have ONE level. but add it to the other levels you already have.

That is also why when you drain your xp with for example the drain from open-blocks, it takes way longer for an level300 to drain than a level10!

**Comment by wolpoff** [comment]
Fair enough.  Understood the mechanic, was just surprised at how small it
was at the time.  The reward text is a little misleading.  It suggests the
addition of one entire level of xp, regardless of your current level.  That
seems easily calculable based on the xp curve equation.  But, sound like
you prefer the smaller first level xp equivalent reward, which is totally
fine.  There are about twenty of them to turn in with that reward in that
block of quests.



-- Ben

**Comment by vincentmet** [comment]
It may be misleading, but this is the vanilla mechanic
