### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by abdullamu** [TheBritishBrotherhood/ArdentCraft-The-Beginning#92]
Hello 
I suggest that simple generators get removed since extra utilities 2 added the same generators plus extra so there no need for two lava generators and 2 netherstars generators etc.

I would also suggest rftools controls get removed since you have steves factory manager they both do the same job but steves factory is very simple yet you can accomplish very complicated mechanics, rf control is bit complicated and you have to have moderate knowledge about programming, math, rf control.

I would like also to suggest adding 
1.Wireless crafting terminal simple yet amazing addon to ae2.
2.Dynamic surround a very beautiful environmental sound effects plus other effect like hunger walking on different blocks etc.

Last suggestion is you either leave ezstorage, refined storage and ae2 in the pack so theres variety and people can choose what they prefer or make progression out of it since it doesnt impact performance unless its used. Or if you really want to remove them leave the quests or config of the quests for people like me who prefer them on. Since the quests are already there.

Thank you cor the hard work

**Comment by TheBritishBrotherhood** [comment]
Very nice list of suggestions! Will definitely look at doing most of these :D 

Please if you have any more suggestions feel free to let me know :D

**Comment by NazT-DragN** [comment]
Ok, I'm a bit confused.
I agree that EZStorage should be left in, (which is why I won't be updating the pack on my end) because with also taking out Iron Chests that leaves no early-game storage other than Storage Drawers which imo is more complicated for a full system since you don't have a GUI in it and EZStorage does.

The part I'm confused about is that while abdullamu suggests leaving in mods to encourage variety and preference choice, they ask to remove "part" of rftools in favor of Steve's Factory Manager since they do the same thing, but here is the problem...the rftools controls are a part of a mod that's needed because rftools deals with Dimension Building and Management, and Steve's Factory Manager helps manage 
the **automation** of mods...not as a means of controlling the "main" thing a mod does. Essentially, if the rftools controls were removed, the mod itself would either not work, or cause crashes when something from that mod was crafted.

Now I'm not a guru with modded MC or anything, I'm just explaining what I've done in the past with those mods.  Storage Drawers works with large numbers of a 'few' types of items, but imo is very impractical to use as a full inventory sorting and storage system, and both RS and AE2 require power and multi-stage fabrication of parts to use, neither of which is available early-game.

@abdullamu unfortunately the first part of your post makes no sense to me, as the end of your post makes for the argument that having different mods that do the same thing adds variety...which is exactly what is happening with having simple generators AND extra utilities 2's generators...different ways of accomplishing something, that gives players a choice of what they want to use.

Sorry @CurtisLee1994 for the long post. Thank you for the hard work you've put into this pack.
I know this is a place to report issues/bugs and not a full forum, but personally I am not happy with the latest update and removal of mods that have no impact on lag (at least not for me, and I'm running a pretty crappy rig). Like I said earlier, I won't be updating the pack, and will play it for as long as I can until something breaks.  I LIKE having the choice to use preferable mods, especially since, like I said, ones that don't have an impact on performance. 

MmmmMmmmMmmmMmmm adds a target dummy which, other than cosmetic, I've never even found a use for so it can go either way, but Iron Chests especially, since all it does is add more slot space to a single chest block, for way less resources than upgrading a wall of Storage Drawers, to get clean sorted storage.

Now while the pack author has full control and can do what they want in terms of what is added/removed...I, as a player (and if there are more that have the same play style as me), chose to install and play this pack because of what's in it.

**Comment by abdullamu** [comment]
Sir im not sure you know alot about rftools mods.

1. Rf control have nothing to do with other mods from rf tools just because the name control doesnt mean it controls rftools mechines, it is new separate mod from rftools made to accomplish the same things steves factory manager, so it doeant affect any signle thing in the pack or anyone since its bit complicated to use. If you really want to use it just add it.

2.About no early game storage theres storage crate from acually addition with small (< really big ), medium and big and have very nice system if you want to move them theres item you place it in the chest and break it which will retain the content of the storage crate. But iron chest is nice too i dont mind if they stay or get removed since ezstorage is not that difficult to get in.

3. Refined storage , ae2 you are right about them except that ae2 can be laggy abit if you have very big network system and its harder to get into due to recipe need certus and charged and flux unlike refined storage plus some people doesnt like the network mechanism of ae2 so that will make not only big but huge difference not like if there simple generators or extra utilites do you really need to use coal generators all the game ?! No so why do you need to have choice in them. We trying to focus on the big things the bigger picture as they say. Plus theres tons of coal generators ender io, acually additions, extra utilities plus some i might have missed.

So my suggestion of removing the mods doesnt impact the gameplay in anyway is just removing stuff that it will not be used by almost anyone.

I hope this makes it clean any other queations let me know.
